### ISSUE TITLE
Distribution class duplications

### ISSUE THREAD

**Issue by AleksanderLevadniy** [aol-public/OneMobileSDK-enVRmnt-videorenderer-android#10]
Maven artifact  `compile 'com.google.vr:sdk-videowidget:1.40.0'` and `envrmnt-library-0.76.aar` has same classes under `com.google.a.a` namespace. Please, resolve this conflict.

**Comment by envrmntPatrickGriffith** [comment]
I think I got this fixed. Check in next build.

**Comment by AleksanderLevadniy** [comment]
@envrmntPatrickGriffith Issue is fixed in latest build
