### ISSUE TITLE
[?] Is it possible to create VrViewController with Context instead of activity? 

### ISSUE THREAD

**Issue by AleksanderLevadniy** [aol-public/OneMobileSDK-enVRmnt-videorenderer-android#2]

**Comment by envrmntPatrickGriffith** [comment]
Here is what I do with the activity in VrViewController's constructor:

mHeartBeat = new HeartBeat( this );

//right here I get the audio manager so you can call mute and unmute (they were part of the controls you wanted)
mAudioManager = (AudioManager)activity.getSystemService(Context.AUDIO_SERVICE);
activity.setVolumeControlStream(AudioManager.STREAM_MUSIC);
//also i get your inflator from the activity so i can add the vrview to your layout.
//i can change this to a 'setVrView(EnvrmntVrVideoView view)' and you manually add it to your layout file and pass it to me
mInflator = activity.getLayoutInflater();
View view = mInflator.inflate(R.layout.vr_view, null);
mVrView = (EnvrmntVrVideoView)view.findViewById(R.id.video_view);


How do you want to proceed?

**Comment by MarkGerl** [comment]
Thanks @envrmntPatrickGriffith ... I'll leave this to @AleksanderLevadniy to answer in the morning.

**Comment by envrmntPatrickGriffith** [comment]
I went ahead and did this:
public VrViewController(Context context, IVrVideoStreamView iVrVideoStreamView){
        mHeartBeat = new HeartBeat( this );
        mAudioManager = (AudioManager)context.getSystemService(Context.AUDIO_SERVICE);
        mIVideoStreamView = iVrVideoStreamView;
    }

    public void setVrView(EnvrmntVrVideoView view){
        mVrView = view;
        //hide icons
        mVrView.setInfoButtonEnabled(false);
        mVrView.setEventListener(new ActivityEventListener());
    }

This allows mute and unmute to work.  Also gets rid of inflating a layout.

ca

**Comment by AleksanderLevadniy** [comment]
@envrmntPatrickGriffith Last code looks like what we need.

Can you post snippet with usage of it inside `MainActivity#onCreate()` method?

**Comment by AleksanderLevadniy** [comment]
When can we expect updated sdk?

**Comment by envrmntPatrickGriffith** [comment]
```


```

**Comment by AleksanderLevadniy** [comment]
In current sdk there is no `EnvrmntVrVideoView` class, is it new?

**Comment by envrmntPatrickGriffith** [comment]
I renamed it, it used to be PanormaicVideoView

**Comment by AleksanderLevadniy** [comment]
🥇 Good, waiting package from you!

**Comment by envrmntPatrickGriffith** [comment]
You want this  loadVideo(Uri videoUri, VrVideoView.Options videoOptions)

to look like this  loadVideo(VRExperience vrExperience)

right?

**Comment by AleksanderLevadniy** [comment]
Yes, that is correct. Also, please, point me out where I can find API to get `VRExperience` using its guid.

**Comment by envrmntPatrickGriffith** [comment]
Yea trying to build it into the sample

**Comment by envrmntPatrickGriffith** [comment]
I wasnt able to finish it yesterday. I will try to get you a build soon.

**Comment by AleksanderLevadniy** [comment]
Ok, waiting for it
