### ISSUE TITLE
Develop approach to load video only by url

### ISSUE THREAD

**Issue by AleksanderLevadniy** [aol-public/OneMobileSDK-enVRmnt-videorenderer-android#3]

**Comment by MarkGerl** [comment]
@AleksanderLevadniy please elaborate .. and assign

**Comment by AleksanderLevadniy** [comment]
By now controller can load video with options, and we have only URL for video.

**Comment by envrmntPatrickGriffith** [comment]
Are you talking about <a href="https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/video/VrVideoView.Options">this</a> 

These are needed for the video to load. So we will need a workaround. I could make a setOptions function separate from the loadVideo function but in the end you sill still have to call it. I could hard code them to HLS and mono video but we all know hardcoding values is not recommended.

**Comment by AleksanderLevadniy** [comment]
@envrmntPatrickGriffith Can you provide method that will playback enVRment id as string instead of  URI + VrVideoView.Options?

**Comment by envrmntPatrickGriffith** [comment]
whats an envrmnt id?

**Comment by AleksanderLevadniy** [comment]
GUID that is used to construct VrExperience instance

**Comment by AleksanderLevadniy** [comment]
Video content provider does not hold url for enVRment videos, instead of url it replies with this id

**Comment by AndriiMoskvin** [comment]
@envrmntPatrickGriffith No, we are using Envrmnt servers for content.

**Comment by AleksanderLevadniy** [comment]
Our servers just holding this GUIDs references.
