### ISSUE TITLE
Remove some methods

### ISSUE THREAD

**Issue by AleksanderLevadniy** [aol-public/OneMobileSDK-enVRmnt-videorenderer-android#4]
```void playbackRateChanged(float newPlaybackRate, float oldPlaybackRate)```
```void onPause()``` - we will call ```pausePlayback```
```void onResume()``` - we will call ```resumePlayback```
```void unknownState()```
```void readyState()```
```void failedState()```

**Comment by envrmntPatrickGriffith** [comment]
pausePlayback and resumePlayback are already there. You just need to call them on the view controller.
If you get life cycle calls for pause resume, make sure you call the pausePlayback and resumePlayback accordingly. Otherwise the video and audio will play in the background.

**Comment by AleksanderLevadniy** [comment]
@envrmntPatrickGriffith Got it
