### ISSUE TITLE
Callbacks implementation

### ISSUE THREAD

**Issue by envrmntPatrickGriffith** [aol-public/OneMobileSDK-enVRmnt-videorenderer-android#8]
I still am not 100% sure you understand how to implement the callbacks.

Here is a quick explanation. If it all makes sense just close this ticket.

On your app side you need to have a class that implements the envrmntsdk's IVrVideoStreamView interface

For refresh here it is and I made it from your interface y ou sent over earlier:
 void unknownState();

    void readyState();

    void failedState();

    void playbackRateChanged(float newPlaybackRate, float oldPlaybackRate);

    void durationDefined(long duration);

    void endOfVideo();

    void playbackReady(boolean ready);

    void bufferedTimeUpdated(float bufferTime);

    void newTime(float timeOnVideo);

For Example: You want to record an analytic event at the end of the video.

First implement this interface on your activity(I am using activity because thats what it is currently, we can discuss changing it later. One Idea is you pass an instance of IVrVideoStreamView) 
You would put the logic that first creates the event and then call the aol analytics service and send the event in the implementation of endOfVideo()

**Comment by AleksanderLevadniy** [comment]
👍 This is exact how I expect it to work. In latest package from you I saw only 
```
public class VrViewController implements com.envrmnt.sdk.IVrVideoStreamView
```
and thought that I must inherit `VrViewController` in order to gain callback events.

```
public VrViewController(Context context, IVrVideoStreamView iVrVideoStreamView)
```
Will do the thing, closing ticket.
