### ISSUE TITLE
Hook up camera orientation 

### ISSUE THREAD

**Issue by AleksanderLevadniy** [aol-public/OneMobileSDK-enVRmnt-videorenderer-android#9]
We are expecting that `VrViewController.setCameraOrientation(lng, lat)` will animate view camera.

Please, notice that angles are in radians.

**Comment by envrmntPatrickGriffith** [comment]
As I stated before. This feature can not be implemented without the Activity based solution.

**Comment by AleksanderLevadniy** [comment]
Nothing to add, closing ticket.
